#########################################################
## REMOVAL PIPELINE                                    ##
#########################################################
##
## This pipeline template is based on the templace 'pipeline.jobs.remove.yml' and contains the custom logic to remove AzureNetAppFiles resources
## that are identified by a special remove-tag.
## In addition to the standard removal logic, the pipeline identifies and removes resources attached to the AzureNetAppFiles (like Volumnes, Pools) and removes
## them in the correct order before attempting to remove the AzureNetAppFiles service itself.
## As such, the script is only capable to remove deployed resource-group level services
##
#################################################################

##---------------------------------------------##
## TEMPLATE PARAMETERS                         ##
##---------------------------------------------##
##
## By default it uses the variables specified in the below [parameters] section. However, you can overwrite these variables in the
##    referencing pipeline by providing the paramater explicitly.
##
## NOTE: If you don't need to overwrite a shared value, you can IGNORE this section
##
##   |==============================================================================================================================================================|
##   | Parameter                  | Default Value          | Description                                                           | Example                        |
##   |----------------------------|------------------------|-----------------------------------------------------------------------|--------------------------------|
##   | displayName                | 'Remove module'        | Name for the pipeline job                                             | 'Remove KeyVault'              |
##   | serviceConnection          | '$(serviceConnection)' | The service connection that connects to Azure                         | 'demo-internal'                |
##   | poolName                   | '$(poolName)'          | You can provide either a [poolname] or [vmImage] to run the job on    | 'Custom Deployment Pool'       |
##   | vmImage                    | '$(vmImage)'           | You can provide either a [poolname] or [vmImage] to run the job on    | 'ubuntu20.04'                  |
##   | defaultJobTimeoutInMinutes | 120                    | The timeout for the job in this pipeline                              | 120                            |
##   | moduleName                 | '$(moduleName)'        | The name of the module to remove                                      | 'KeyVault'                     |
##   | modulePath                 | '$(modulePath)'        | The path to the module to deploy. E.g. [$(modulesPath)/$(moduleName)] | '$(modulesPath)/$(moduleName)' |
##   | resourceGroupName          | '$(resourceGroupName)' | The resourcegroup to remove the resource from                         | 'validation-rg'                |
##   |==============================================================================================================================================================|
##
##---------------------------------------------##

parameters:
  # Pipeline-related parameters
  displayName: "Remove module"
  serviceConnection: "$(serviceConnection)"
  poolName: "$(poolName)"
  vmImage: "$(vmImage)"
  defaultJobTimeoutInMinutes: 120

  # Logic-related parameters
  moduleName: "$(moduleName)"
  modulePath: '$(modulePath)'
  resourceGroupName: "$(resourceGroupName)"

##---------------------------------------------##
## TEMPLATE LOGIC                              ##
##---------------------------------------------##
jobs:
  - job:
    displayName: ${{ parameters.displayName }}
    timeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}
    pool:
      ${{ if ne(parameters.vmImage, '') }}:
        vmImage: ${{ parameters.vmImage }}
      ${{ if ne(parameters.poolName, '') }}:
        name: ${{ parameters.poolName }}
    steps:
      - task: AzurePowerShell@4
        displayName: "Remove [${{ parameters.moduleName }}] in [${{ parameters.resourceGroupName }}] via [${{ parameters.serviceConnection }}]"
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          azurePowerShellVersion: LatestVersion
          ScriptType: InlineScript
          failOnStandardError: false
          inline: |
            # ---------------------------- #
            # HANDLE MULTI-REPO INVOCATION #
            # ---------------------------- #
            $componentsBasePath = "$(System.DefaultWorkingDirectory)"
    
            if( "${{ join(';',parameters.checkoutRepositories) }}".length -gt 0) {
              $componentsBasePath = Join-Path $componentsBasePath '$(modulesRepository)'
            }
          
            # -------------- #
            # INVOKE REMOVAL #
            # -------------- #
            . "$componentsBasePath/${{ parameters.modulePath }}/Scripts/Remove-NetAppAccount.ps1"
    
            $functionInput = @{
              moduleName            = '${{ parameters.moduleName }}'
              resourceGroupName     = '${{ parameters.resourceGroupName }}'
            }
    
            Write-Verbose "Invoke task with" -Verbose
            $functionInput
    
            Remove-NetAppAccount @functionInput -Verbose
  