#########################################################
## DEPLOYMENT PIPELINE                                 ##
#########################################################
##
## This pipeline template contains the logic to deploy a given module's ARM template using the provided parameter file(s) 
##
## Enabled levels of deployment
## - Resource-Group-Level
## - Subscription-Level
## - Management-Group-Level
## - Tenant-Level
##
#########################################################
##
##---------------------------------------------##
## TEMPLATE PARAMETERS                         ##
##---------------------------------------------##
##
## By default it uses the variables specified in the below [parameters] section. However, you can overwrite these variables in the 
##    referencing pipeline by providing the parameter explicitly.
## 
## NOTE: If you don't need to overwrite a shared value, you can IGNORE this section 
##
##   |=================================================================================================================================================================================================================================|
##   | Parameter                       | Default Value                        | Description                                                                                               | Example                                    |
##   |---------------------------------|--------------------------------------|-----------------------------------------------------------------------------------------------------------|--------------------------------------------|
##   | serviceConnection               | '$(serviceConnection)'               | The service connection that connects to Azure                                                             | 'demo-internal'                            |
##   | removeDeployment                | '$(removeDeployment)'                | Set to [true] to flag resource for removal. If not provided, defaults to false.                           | 'true'                                     |
##   | poolName                        | '$(poolName)'                        | You can provide either a [poolname] or [vmImage] to run the job on                                        | 'Custom Deployment Pool'                   |
##   | vmImage                         | '$(vmImage)'                         | You can provide either a [poolname] or [vmImage] to run the job on                                        | 'ubuntu20.04'                              |
##   | defaultJobTimeoutInMinutes      | 120                                  | The timeout for the job in this pipeline                                                                  | 120                                        |
##   | checkoutRepositories            | ''                                   | An optional list of repositories to check out at the beginning of this job in addition to the source      | 'Components'                               |
##   | moduleName                      | '$(moduleName)'                      | The name of the module to deploy                                                                          | 'KeyVault'                                 |
##   | modulePath                      | '$(modulePath)'                      | The path to the module to deploy. E.g. [$(modulesPath)/$(moduleName)]                                     | '$(modulesPath)/$(moduleName)'             |
##   | modulesPath                     | '$(modulesPath)'                     | The path to the modules folder root (one level above [modulePath])                                        | 'Modules/ARM'                              |
##   | parametersPath                  | '$(parametersPath)'                  | The path to the modules parameter file                                                                    | '$(modulePath)/Parameters'                 |
##   | deploymentBlocks                |                                      | The parameter file(s) to deploy with. Must be provided                                                    | path: '$(parametersPath)/parameters.json'  |
##   | parametersRepository            | '$(Build.Repository.Name)'           | The respository with the parameter files. Defaults to the triggering repository                           | 'Solutions'                                |
##   | location                        | '$(location)'                        | The location to deploy with                                                                               | 'EastUs2'                                  |
##   | resourceGroupName               | '$(resourceGroupName)'               | The resourcegroup to deploy into. Required only for Resource-Group-Level deployments                      | 'validation-rg'                            |
##   | subscriptionId                  | '$(subscriptionId)'                  | The id of the subscription to deploy into when using a Management group service connection                | 'aed7c000-6387-412e-bed0-24dfddf4bbc6'     |
##   | managementGroupId               | '$(managementGroupId)'               | The id of the management group to deploy into. Required only for Management-Group-Level deployments       | '6ycc9620-cb01-454f-9ebc-fc6b1df48d64'     |
##   | azurePowerShellVersion          | '$(azurePowerShellVersion)'          | Used for configuring the Azure PowerShellModules Version, one of the example values.                      | 'latestVersion' or 'OtherVersion'          |
##   | preferredAzurePowerShellVersion | '$(preferredAzurePowerShellVersion)' | Used for configuring the Azure PowerShellModules Version, either an empty string or the specific version. | '4.4.0'                                    |
##   |=================================================================================================================================================================================================================================|
##
##---------------------------------------------##

parameters:
  
  # Pipeline-related parameters
  serviceConnection: '$(serviceConnection)'
  poolName: '$(poolName)'
  vmImage: '$(vmImage)'
  defaultJobTimeoutInMinutes: 120
  checkoutRepositories: ''
  dependsOn: []
  # Logic-related parameters
  removeDeployment: false
  moduleName: '$(moduleName)'
  modulePath: '$(modulePath)'
  parametersPath: '$(parametersPath)'
  modulesPath: '$(modulesPath)'
  deploymentBlocks: ''
  parametersRepository: '$(Build.Repository.Name)'
  location: '$(location)'
  resourceGroupName: '$(resourceGroupName)'
  subscriptionId: "$(subscriptionId)"
  managementGroupId: '$(managementGroupId)'
  # Azure PowerShell Version parameters
  azurePowerShellVersion: '$(azurePowerShellVersion)'
  preferredAzurePowerShellVersion: '$(preferredAzurePowerShellVersion)'
  # Pipeline Orchestrated (Key Vault) Parameters
  pokv: false # Switch to enable temporary POKV deployment
  modulesRepository: '$(modulesRepository)'
  keyVaultName: '$(keyVaultName)'
  artifactName: '$(artifactName)'  
  environment: '$(environment)'
  secretsFilter: '$(secretsFilter)'
  templateFile: '$(templateFile)' 
  parametersFile: '$(parametersFile)'
  overrideParameters: '$(overrideParameters)'
  scriptArguments: '$(scriptArguments)'

##---------------------------------------------##
## TEMPLATE LOGIC                              ##
##---------------------------------------------##

jobs:
- ${{ if eq(parameters.pokv, 'false') }}:
  - ${{ each deploymentBlock in parameters.deploymentBlocks }}:
    - job: ${{ deploymentBlock.jobName }}
  
      ${{ if ne( deploymentBlock.displayName, '') }}:
        displayName: ${{ deploymentBlock.displayName }}
      ${{ if eq( deploymentBlock.displayName, '') }}:
        displayName: Deploy with [${{ replace( deploymentBlock.path, '$(parametersPath)', '') }}]
      timeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}
      ${{ if ne( parameters.dependsOn, '') }}:
        dependsOn: ${{ parameters.dependsOn }}
      pool:
        ${{ if ne(parameters.vmImage, '') }}:
          vmImage: ${{ parameters.vmImage }}
        ${{ if ne(parameters.poolName, '') }}:
          name: ${{ parameters.poolName }}

      steps:

      # [Checkout Repositories] task(s)
      #--------------------------------
      - checkout: self
      - ${{ if ne(parameters.checkoutRepositories, '') }}:
        - ${{ each checkoutRepository in parameters.checkoutRepositories }}:
          - checkout: ${{ checkoutRepository }}
            fetchDepth: 1  # the depth of commits to ask Git to fetch; if not set defaults to no limit
            path: 's/${{ checkoutRepository }}'
            
      # [Deployment] task(s)
      #--------------------------------
      - task: AzurePowerShell@5
        displayName: 'Deploy [${{ parameters.moduleName }}] via connection [${{ parameters.serviceConnection }}]'
        inputs:
          azureSubscription:  ${{ parameters.serviceConnection }}
          azurePowerShellVersion: ${{ parameters.azurePowerShellVersion }}
          preferredAzurePowerShellVersion: ${{ parameters.preferredAzurePowerShellVersion }}
          pwsh: true
          ScriptType: InlineScript
          inline: |
            # ---------------------------- #
            # HANDLE MULTI-REPO INVOCATION #
            # ---------------------------- #
            $componentsBasePath = "$(System.DefaultWorkingDirectory)"
            $parametersBasePath = "$(Build.Repository.LocalPath)"

            if( "${{ join(';',parameters.checkoutRepositories) }}".length -gt 0) {
              $componentsBasePath = Join-Path $componentsBasePath '$(modulesRepository)'
              $parametersBasePath = "$(Build.Repository.LocalPath)/${{ parameters.parametersRepository }}"
            }

            # Load used functions
            . "$(System.DefaultWorkingDirectory)/$(templateFunctionsPath)/New-ModuleDeployment.ps1"
            
            # ----------------- #
            # INVOKE DEPLOYMENT #
            # ----------------- #
            $functionInput = @{
              moduleName         = '${{ parameters.moduleName }}'
              componentsBasePath = $componentsBasePath
              parametersBasePath = $parametersBasePath 
              modulePath         = '${{ parameters.modulePath }}' 
              parameterFilePath  = '${{ deploymentBlock.path }}' 
              location           = '${{ parameters.location }}' 
              resourceGroupName  = '${{ parameters.resourceGroupName }}'
              subscriptionId     = '${{ parameters.subscriptionId }}'
              managementGroupId  = '${{ parameters.managementGroupId }}'
              # Note: if parameter is like "`$(removeDeployment*" it was not set as the variable was not resolved
              removeDeployment   = ('${{ parameters.removeDeployment }}' -like "`$(removeDeployment*") ? $false : [System.Convert]::ToBoolean('${{ parameters.removeDeployment }}')
            }

            Write-Verbose "Invoke task with" -Verbose
            $functionInput

            New-ModuleDeployment @functionInput -Verbose

# [PipelineOrhcestrated (KeyVault)] Deployment
#-------------------------------------------
- ${{ if eq(parameters.pokv, 'true') }}:
  - ${{ each deploymentBlock in parameters.deploymentBlocks }}:
    - deployment:
      ${{ if ne( deploymentBlock.displayName, '') }}:
        displayName: ${{ deploymentBlock.displayName }}
      pool:
        ${{ if ne(parameters.vmImage, '') }}:
          vmImage: ${{ parameters.vmImage }}
        ${{ if ne(parameters.poolName, '') }}:
          name: ${{ parameters.poolName }}
      dependsOn: '${{ parameters.dependsOn }}'
      environment: '${{ parameters.environment }}'
      workspace:
        clean: all
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            - checkout: self
            - ${{ if ne(parameters.checkoutRepositories, '') }}:
              - ${{ each checkoutRepository in parameters.checkoutRepositories }}:
                - checkout: ${{ checkoutRepository }}
                  fetchDepth: 1  # the depth of commits to ask Git to fetch; if not set defaults to no limit
                  path: 's/${{ checkoutRepository }}'

            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: '${{ parameters.artifactName}}'
                downloadPath: $(System.ArtifactsDirectory)

            - task: AzurePowerShell@5
              displayName: Resolve $ENV Variables in ${{ parameters.parametersFile }}
              inputs:
                azureSubscription: '${{ parameters.serviceConnection }}'
                ScriptType: 'InlineScript'
                Inline: |
                  $KeyVaultName = $ENV:KEYVAULTNAME
                  $secrets = ${{ parameters.secretsFilter }}
                  Write-Verbose "DEBUG: secrets -> $secrets <-" -verbose
                  if ($secrets) {
                    $array = $secrets.Split(',')
                    Foreach ($key in $array) {
                      Write-Host "Secret Key Filter is $key"
                      $secret = Get-AzKeyVaultSecret -VaultName $(KeyVaultName) -Name "$key" -AsPlainText
                      Write-Host "##vso[task.setvariable variable=$key;]$secret"
                      New-Variable -Scope Global -Name "$key" -Value "$secret" -Force
                      }  
                  }
                  $parametersFile = Get-Content "${{ parameters.parametersFile }}" | ForEach-Object { if ($_ -match "$") {$ExecutionContext.InvokeCommand.ExpandString($_)} else {$_}}
                  Set-Content -Path "${{ parameters.parametersFile }}" -Value $parametersFile -Force
                  # Display File contents (to assist with debugging)
                  Get-Content "${{ parameters.parametersFile }}"
                azurePowerShellVersion: 'LatestVersion'
                pwsh: true

            - task: AzureResourceGroupDeployment@2
              displayName: 'Deploy ${{ parameters.moduleName }}'
              inputs:
                azureSubscription: '${{ parameters.serviceConnection }}'
                resourceGroupName: '${{ parameters.resourceGroupName }}'
                location: '${{ parameters.location }}'
                csmFile: '${{ parameters.templateFile }}'
                csmParametersFile: '${{ parameters.parametersFile }}'
                overrideParameters: '${{ parameters.overrideParameters }}'
                deploymentMode: Incremental
                deploymentOutputs: resourceGroupDeploymentOutputs

            - task: PowerShell@2
              displayName: 'Set Secrets for [${{ parameters.moduleName }}]'            
              inputs:
                targetType: 'inline'
                pwsh: true
                script: |
                  Write-Host "env:RESOURCEGROUPDEPLOYMENTOUTPUTS: $($ENV:RESOURCEGROUPDEPLOYMENTOUTPUTS)"
                  Write-Host "resourceGroupDeploymentOutputs: $(resourceGroupDeploymentOutputs)"

                  # Load used functions
                  . "$(System.DefaultWorkingDirectory)/$(templateFunctionsPath)/Set-AKVSecrets.ps1"

                  $KeyVaultName = $ENV:KEYVAULTNAME
                  $moduleName = "${{ parameters.moduleName }}"
                  $armOutputs = (ConvertFrom-Json $ENV:RESOURCEGROUPDEPLOYMENTOUTPUTS)

                  InjectDeploymentOutputs -KeyVaultName $KeyVaultName -ModuleName $ModuleName -ArmOutputs $armOutputs