#########################################################
## VALIDATION PIPELINE                                 ##
#########################################################
##
## This pipeline template contains the logic to validate a given modue's ARM template using the provided parameter file(s) 
##
## Enabled levels of validation
## - Resource-Group-Level
## - Subscription-Level
## - Management-Group-Level
## - Tenant-Level
##
#########################################################
##
##---------------------------------------------##
## TEMPLATE PARAMETERS                         ##
##---------------------------------------------##
##
## By default it uses the variables specified in the below [parameters] section. However, you can overwrite these variables in the 
##    referencing pipeline by providing the parameter explicitly. 
##
## NOTE: If you don't need to overwrite a shared value, you can IGNORE this section 
##
##   |=================================================================================================================================================================================================================================|
##   | Parameter                       | Default Value                        | Description                                                                                               | Example                                    |
##   |---------------------------------|--------------------------------------|-----------------------------------------------------------------------------------------------------------|--------------------------------------------|
##   | serviceConnection               | '$(serviceConnection)'               | The service connection that connects to Azure                                                             | 'demo-internal'                            |
##   | poolName                        | '$(poolName)'                        | You can provide either a [poolname] or [vmImage] to run the job on                                        | 'Custom Deployment Pool'                   |
##   | vmImage                         | '$(vmImage)'                         | You can provide either a [poolname] or [vmImage] to run the job on                                        | 'ubuntu20.04'                              |
##   | defaultJobTimeoutInMinutes      | 120                                  | The timeout for the job in this pipeline                                                                  | 120                                        |
##   | checkoutRepositories            | ''                                   | An optional list of repositories to check out at the beginning of this job in addition to the source      | 'Components'                               |
##   | moduleName                      | '$(moduleName)'                      | The name of the module to validate                                                                        | 'KeyVault'                                 |
##   | modulePath                      | '$(modulePath)'                      | The path to the module to validate. E.g. [$(modulesPath)/$(moduleName)]                                   | '$(modulesPath)/$(moduleName)'             |
##   | modulesPath                     | '$(modulesPath)'                     | The path to the modules folder root (one level above [modulePath])                                        | 'Modules/ARM'                              |
##   | parametersPath                  | '$(parametersPath)'                  | The path to the modules parameter file                                                                    | '$(modulePath)/Parameters'                 |
##   | deploymentBlocks                |                                      | The parameter file(s) to validate with. Must be provided                                                  | '$(parametersPath)/parameters.json'        |
##   | parametersRepository            | '$(Build.Repository.Name)'           | The respository with the parameter files. Defaults to the triggering repository                           | 'Solutions'                                |                                  
##   | location                        | '$(location)'                        | The location to validate with                                                                             | 'France Central'                           |
##   | resourceGroupName               | '$(resourceGroupName)'               | The resourcegroup to validate into. Required only for Resource-Group-Level validations                    | 'validation-rg'                            |
##   | subscriptionId                  | '$(subscriptionId)'                  | The id of the subscription to validate with when using a Management group service connection              | 'aed7c000-6387-412e-bed0-24dfddf4bbc6'     |
##   | managementGroupId               | '$(managementGroupId)'               | The id of the management group to validate with. Required only for Management-Group-Level validations     | '477c9620-cb01-454f-9ebc-fc6b1df48c14'     |
##   | azurePowerShellVersion          | '$(azurePowerShellVersion)'          | Used for configuring the Azure PowerShellModules Version, one of the example values.                      | 'latestVersion' or 'OtherVersion'          |
##   | preferredAzurePowerShellVersion | '$(preferredAzurePowerShellVersion)' | Used for configuring the Azure PowerShellModules Version, either an empty string or the specific version. | '4.4.0'                                    |
##   |=================================================================================================================================================================================================================================|
##
##---------------------------------------------##

parameters:
  # Pipeline-related parameters
  serviceConnection: '$(serviceConnection)'
  poolName: '$(poolName)'
  vmImage: '$(vmImage)'
  defaultJobTimeoutInMinutes: 120
  checkoutRepositories: ''
  # Logic-related parameters
  moduleName: '$(moduleName)'
  modulePath: '$(modulePath)'
  modulesPath: '$(modulesPath)'
  parametersPath: '$(parametersPath)'
  deploymentBlocks: 
  parametersRepository: '$(Build.Repository.Name)'
  location: '$(location)'
  resourceGroupName: '$(resourceGroupName)'
  subscriptionId: '$(subscriptionId)'
  managementGroupId: '$(managementGroupId)'
  # Azure PowerShell Version parameter
  azurePowerShellVersion: '$(azurePowerShellVersion)'
  preferredAzurePowerShellVersion: '$(preferredAzurePowerShellVersion)'

##---------------------------------------------##
## TEMPLATE LOGIC                              ##
##---------------------------------------------##
jobs:
- job:
  displayName: Run module tests
  timeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}
  pool:
    ${{ if ne(parameters.vmImage, '') }}:
      vmImage: ${{ parameters.vmImage }}
    ${{ if ne(parameters.poolName, '') }}:
      name: ${{ parameters.poolName }}
  steps:
  # [Checkout Repositories] task(s)
  #--------------------------------
  - checkout: self
  - ${{ if ne(parameters.checkoutRepositories, '') }}:
    - ${{ each checkoutRepository in parameters.checkoutRepositories }}:
      - checkout: ${{ checkoutRepository }}
        fetchDepth: 1  # the depth of commits to ask Git to fetch; if not set defaults to no limit
        path: 's/${{ checkoutRepository }}'

  # [Module Pester Test] task(s)
  #-----------------------------
  - task: PowerShell@2
    displayName: Run [${{ parameters.moduleName }}] tests via (Pester)
    inputs:
      targetType: inline
      pwsh: true
      script: |      
        # ---------------------------- #
        # HANDLE MULTI-REPO INVOCATION #
        # ---------------------------- #
        $componentsBasePath = "$(System.DefaultWorkingDirectory)"
        # Handle multiple-repositories
        if( "${{ join(';',parameters.checkoutRepositories) }}".length -gt 0) {
          Write-Verbose "Multi Repo" -Verbose 
          $componentsBasePath = Join-Path $componentsBasePath '$(modulesRepository)'
        }

        # --------------------- #
        # INVOKE PESTER TEST(S) #
        # --------------------- #
        Install-Module Pester -Force -ErrorAction Stop -RequiredVersion 5.1.1 
  
        Invoke-Pester -Configuration @{
          Run        = @{
            Path = "$componentsBasePath/${{ parameters.modulePath }}/Tests/*.tests.ps1"
          }
          TestResult = @{
            TestSuiteName = 'Module Tests'
            OutputPath    = '$(System.DefaultWorkingDirectory)/module-testResults.xml'
            OutputFormat  = 'NUnitXml'
            Enabled       = $true
          } 
          Output     = @{
            Verbosity = 'Detailed'
          }
        }
      errorActionPreference: continue

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunTitle: "Module Tests"
      testResultsFormat: NUnit
      testResultsFiles: module-testResults.xml
      failTaskOnFailedTests: false
    continueOnError: false
    condition: succeededOrFailed()

- job:
  displayName: Run global tests
  timeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}
  pool:
    ${{ if ne(parameters.vmImage, '') }}:
      vmImage: ${{ parameters.vmImage }}
    ${{ if ne(parameters.poolName, '') }}:
      name: ${{ parameters.poolName }}
  steps:
  # [Checkout Repositories] task(s)
  #--------------------------------
  - checkout: self
  - ${{ if ne(parameters.checkoutRepositories, '') }}:
    - ${{ each checkoutRepository in parameters.checkoutRepositories }}:
      - checkout: ${{ checkoutRepository }}
        fetchDepth: 1  # the depth of commits to ask Git to fetch; if not set defaults to no limit
        path: 's/${{ checkoutRepository }}'

  # [Module Pester Test] task(s)
  #-----------------------------
  - task: PowerShell@2
    displayName: Run global [${{ parameters.moduleName }}] tests via (Pester)
    inputs:
      targetType: inline
      pwsh: true
      script: |      
        # ---------------------------- #
        # HANDLE MULTI-REPO INVOCATION #
        # ---------------------------- #
        $componentsBasePath = "$(System.DefaultWorkingDirectory)"
        # Handle multiple-repositories
        if( "${{ join(';',parameters.checkoutRepositories) }}".length -gt 0) {
          Write-Verbose "Multi Repo" -Verbose 
          $componentsBasePath = Join-Path $componentsBasePath '$(modulesRepository)'
        }

        # --------------------- #
        # INVOKE PESTER TEST(S) #
        # --------------------- #
        Install-Module Pester -Force -ErrorAction Stop -RequiredVersion 5.1.1 
  
        Invoke-Pester -Configuration @{
          Run        = @{
            Container = New-PesterContainer -Path '$(System.DefaultWorkingDirectory)/Modules/ARM/.global/global.module.tests.ps1' -Data @{ 
              moduleFolderPaths = "$componentsBasePath/${{ parameters.modulePath }}"
            }
          }
          Filter     = @{
            ExcludeTag = 'ApiCheck'
          }
          TestResult = @{
            TestSuiteName = 'Global Module Tests'
            OutputPath    = '$(System.DefaultWorkingDirectory)/Modules/ARM/.global/global-testResults.xml'
            OutputFormat  = 'NUnitXml'
            Enabled       = $true
          } 
          Output     = @{
            Verbosity = 'Detailed'
          }
        }
      errorActionPreference: continue

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunTitle: "Global Module Tests"
      testResultsFormat: NUnit
      testResultsFiles: global-testResults.xml
      failTaskOnFailedTests: false
      searchFolder: '$(System.DefaultWorkingDirectory)/Modules/ARM/.global'
    continueOnError: false
    condition: succeededOrFailed()

- job:
  displayName: Run global API tests
  timeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}
  pool:
    ${{ if ne(parameters.vmImage, '') }}:
      vmImage: ${{ parameters.vmImage }}
    ${{ if ne(parameters.poolName, '') }}:
      name: ${{ parameters.poolName }}
  steps:
  # [Checkout Repositories] task(s)
  #--------------------------------
  - checkout: self
  - ${{ if ne(parameters.checkoutRepositories, '') }}:
    - ${{ each checkoutRepository in parameters.checkoutRepositories }}:
      - checkout: ${{ checkoutRepository }}
        fetchDepth: 1  # the depth of commits to ask Git to fetch; if not set defaults to no limit
        path: 's/${{ checkoutRepository }}'

  # [Module Pester Test] task(s)
  #-----------------------------
  - task: AzurePowerShell@4
    displayName: Run [${{ parameters.moduleName }}] API tests via (Pester)
    inputs:
      azureSubscription: $(serviceConnection)
      azurePowerShellVersion: LatestVersion
      ScriptType: InlineScript
      pwsh: true
      inline: |     
        # ---------------------------- #
        # HANDLE MULTI-REPO INVOCATION #
        # ---------------------------- #
        $componentsBasePath = "$(System.DefaultWorkingDirectory)"
        # Handle multiple-repositories
        if( "${{ join(';',parameters.checkoutRepositories) }}".length -gt 0) {
          Write-Verbose "Multi Repo" -Verbose 
          $componentsBasePath = Join-Path $componentsBasePath '$(modulesRepository)'
        }

        # --------------------- #
        # INVOKE PESTER TEST(S) #
        # --------------------- #
        Install-Module Pester -Force -ErrorAction Stop -RequiredVersion 5.1.1 

        Invoke-Pester -Configuration @{
          Run        = @{
            Container = New-PesterContainer -Path '$(System.DefaultWorkingDirectory)/Modules/ARM/.global/global.module.tests.ps1' -Data @{ 
              moduleFolderPaths = "$componentsBasePath/${{ parameters.modulePath }}"
            }
          }
          Filter     = @{
            Tag = 'ApiCheck'
          }
          TestResult = @{
            TestSuiteName = 'Global Module API Tests'
            OutputPath    = '$(System.DefaultWorkingDirectory)/Modules/ARM/.global/api-testResults.xml'
            OutputFormat  = 'NUnitXml'
            Enabled       = $true
          } 
          Output     = @{
            Verbosity = 'Detailed'
          }
        }
      errorActionPreference: continue

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunTitle: "Global Module API Tests"
      testResultsFormat: NUnit
      testResultsFiles: api-testResults.xml
      failTaskOnFailedTests: false
      searchFolder: '$(System.DefaultWorkingDirectory)/Modules/ARM/.global'
    continueOnError: false
    condition: succeededOrFailed()

- ${{ each deploymentBlock in parameters.deploymentBlocks }}:
  - job:
    ${{ if ne( deploymentBlock.displayName, '') }}:
      displayName: ${{ deploymentBlock.displayName }}
    ${{ if eq( deploymentBlock.displayName, '') }}:
      displayName: Validate with [${{ replace( deploymentBlock.path, '$(parametersPath)', '') }}]
    timeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}
    pool:
      ${{ if ne(parameters.vmImage, '') }}:
        vmImage: ${{ parameters.vmImage }}
      ${{ if ne(parameters.poolName, '') }}:
        name: ${{ parameters.poolName }}
    steps:
    # [Checkout Repositories] task(s)
    #--------------------------------
    - checkout: self
    - ${{ if ne(parameters.checkoutRepositories, '') }}:
      - ${{ each checkoutRepository in parameters.checkoutRepositories }}:
        - checkout: ${{ checkoutRepository }}
          fetchDepth: 1  # the depth of commits to ask Git to fetch; if not set defaults to no limit
          path: 's/${{ checkoutRepository }}'

    # [Test Deployment] task(s)
    #--------------------------
    - task: AzurePowerShell@5
      displayName: 'Validate [${{ parameters.moduleName }}] via connection [${{ parameters.serviceConnection }})]'
      inputs:
        azureSubscription: ${{ parameters.serviceConnection }}
        azurePowerShellVersion: ${{ parameters.azurePowerShellVersion }}
        preferredAzurePowerShellVersion: ${{ parameters.preferredAzurePowerShellVersion }}
        ScriptType: InlineScript
        pwsh: true
        inline: |
          # ---------------------------- #
          # HANDLE MULTI-REPO INVOCATION #
          # ---------------------------- #
          $componentsBasePath = "$(System.DefaultWorkingDirectory)"
          $parametersBasePath = "$(Build.Repository.LocalPath)"

          if( "${{ join(';',parameters.checkoutRepositories) }}".length -gt 0) {
            $componentsBasePath = Join-Path $componentsBasePath '$(modulesRepository)'
            $parametersBasePath = "$(Build.Repository.LocalPath)/${{ parameters.parametersRepository }}"
          }

          # Load used functions
          . "$(System.DefaultWorkingDirectory)/$(templateFunctionsPath)/Test-TemplateWithParameterFile.ps1"

          # ----------- #
          # INVOKE TEST #
          # ----------- #
          $functionInput = @{
            componentsBasePath = $componentsBasePath
            parametersBasePath = $parametersBasePath 
            modulePath         = '${{ parameters.modulePath }}' 
            parameterFilePath  = '${{ deploymentBlock.path }}' 
            location           = '${{ parameters.location }}' 
            resourceGroupName  = '${{ parameters.resourceGroupName }}'
            subscriptionId     = '${{ parameters.subscriptionId }}'
            managementGroupId  = '${{ parameters.managementGroupId }}'
          }

          Write-Verbose "Invoke task with" -Verbose
          $functionInput

          Test-TemplateWithParameterFile @functionInput -Verbose